/*import {Weapon} from './Weapon';

export const WEAPONS: Weapon[]= [
new Weapon({'Weapon Name':'Dagger','Weapon Type':'Dagger','Str':'14','Dex':'98','Int':'0','Faith':'0','Luck':'0','BasePhysical':'116','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'9','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Heavy Dagger','Weapon Type':'Dagger','Str':'100.8','Dex':'0','Int':'0','Faith':'0','Luck':'0','BasePhysical':'107.3','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'9','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Sharp Dagger','Weapon Type':'Dagger','Str':'5.5','Dex':'147','Int':'0','Faith':'0','Luck':'0','BasePhysical':'107.3','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'9','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Refined Dagger','Weapon Type':'Dagger','Str':'84.8','Dex':'84.8','Int':'0','Faith':'0','Luck':'0','BasePhysical':'104.4','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'8','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Simple Dagger','Weapon Type':'Dagger','Str':'13','Dex':'91','Int':'112','Faith':'0','Luck':'0','BasePhysical':'63','BaseMagic':'72.45','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Crystal Dagger','Weapon Type':'Dagger','Str':'10','Dex':'70','Int':'132','Faith':'0','Luck':'0','BasePhysical':'59.85','BaseMagic':'81.9','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Fire Dagger','Weapon Type':'Dagger','Str':'0','Dex':'0','Int':'0','Faith':'0','Luck':'0','BasePhysical':'120.45','BaseMagic':'0','BaseFire':'120','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Chaos Dagger','Weapon Type':'Dagger','Str':'12','Dex':'84','Int':'88','Faith':'88','Luck':'0','BasePhysical':'63','BaseMagic':'0','BaseFire':'82','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Lightning Dagger','Weapon Type':'Dagger','Str':'10','Dex':'70','Int':'0','Faith':'132','Luck':'0','BasePhysical':'59.85','BaseMagic':'0','BaseFire':'0','BaseLightning':'82','BaseDark':'0','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Deep Dagger','Weapon Type':'Dagger','Str':'0','Dex':'0','Int':'0','Faith':'0','Luck':'0','BasePhysical':'120.45','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'120','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Dark Dagger','Weapon Type':'Dagger','Str':'12','Dex':'84','Int':'88','Faith':'88','Luck':'0','BasePhysical':'63','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'82','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Poison Dagger','Weapon Type':'Dagger','Str':'14','Dex':'98','Int':'0','Faith':'0','Luck':'0','BasePhysical':'89.9','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'9','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Blood Dagger','Weapon Type':'Dagger','Str':'14','Dex':'98','Int':'0','Faith':'0','Luck':'0','BasePhysical':'89.9','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'9','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Raw Dagger','Weapon Type':'Dagger','Str':'0','Dex':'0','Int':'0','Faith':'0','Luck':'0','BasePhysical':'145','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'9','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name':'Blessed Dagger','Weapon Type':'Dagger','Str':'11','Dex':'77','Int':'0','Faith':'104','Luck':'0','BasePhysical':'81.9','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'9','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'}),
new Weapon({'Weapon Name': 'Dark Falchion', 'Weapon Type': 'Curved Sword', 'Str': '30', 'Dex': '54', 'Int': '77', 'Faith': '77', 'Luck': '0', 'BasePhysical': '112', 'BaseMagic': '0', 'BaseFire': '0', 'BaseLightning': '0', 'BaseDark': '145.6', 'PhysicalIndex': '0', 'MagicIndex': '0', 'FireIndex': '0', 'LightningIndex': '0', 'DarkIndex': '0'}),
new Weapon({'Weapon Name':'Rapier','Weapon Type':'Thrusting Sword','Str':'28','Dex':'84','Int':'0','Faith':'0','Luck':'0','BasePhysical':'190','BaseMagic':'0','BaseFire':'0','BaseLightning':'0','BaseDark':'0','PhysicalIndex':'0','MagicIndex':'0','FireIndex':'0','LightningIndex':'0','DarkIndex':'0'})
];*/
